Repository AguaClara/aguaclara, pull requests merged in 2019-02, with the labels that each got.

#161 Floc rewrite to include entrance tank
  aguaclara/design/floc.py
  aguaclara/design/plant.py
  setup.py
  tests/design/test_floc.py
  tests/design/test_plant.py
Labels: aide_design, feature

#160 Optimize aguaclara.play
  aguaclara/play.py
Labels: feature

#169 Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: feature

#171 v0.0.20
  aguaclara/core/physchem.py
  aguaclara/design/floc.py
  aguaclara/design/plant.py
  aguaclara/play.py
  setup.py
  tests/design/test_floc.py
  tests/design/test_plant.py
Labels: release
